export const PERMISSIONS = {
  USERS_CREATE: 'users:create',
  USERS_READ: 'users:read',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  REPORTS_TODAY_VIEW: 'reportsToday:view',
  REPORTS_PERIOD_VIEW: 'reportsPeriod:view',
  CHECK_CREATE: 'check:create',
  CHECK_VOID: 'check:void',
  CHECK_CLOSED_VOID: 'check.closed:void',
  CHECK_ITEM_VOID: 'check.item:void',
  CHECK_ITEM_PRINTED_VOID: 'check.item.printed:void',
  CHECK_PRINT: 'check:print',
  CHECK_REPRINT: 'check:reprint',
  CHECK_CLOSE: 'check:close',
  CHECK_OFFICER_CLOSE: 'check.officer:close',
  CHECK_SEPERATE: 'check:seperate',
  CHECK_PRINTED_SEPERATE: 'check.printed:seperate',
  CHECK_ITEM_TRANSFER: 'check.item:transfer',
  CHECK_PRINTED_ITEM_TRANSFER: 'check.printed.item:transfer',
  CHECK_TABLE_TRANSFER: 'check.table:transfer',
  CHECK_MERGE: 'check:merge',
  CHECK_PRINTED_MERGE: 'check.printed:merge',
  CHECK_COMP: 'check:comp',
  CHECK_PRINTED_COMP: 'check.printed:comp',
  CHECK_ITEM_COMP: 'check.item:comp',
  CHECK_PRINTED_ITEM_COMP: 'check.printed.item:comp',
  MINIMUM_CHARGE_APPLY: 'minimumCharge:apply',
  DISCOUNT_APPLY: 'discount:apply',
  DISCOUNT_PRINTED_APPLY: 'discount.printed:apply',
  DISCOUNT_VALUE_APPLY: 'discount.value:apply',
  DISCOUNT_PERCENT1_APPLY: 'discount.percent1:apply',
  DISCOUNT_PERCENT2_APPLY: 'discount.percent2:apply',
  DISCOUNT_PERCENT3_APPLY: 'discount.percent3:apply',
  DISCOUNT_PERCENT4_APPLY: 'discount.percent4:apply',
  DISCOUNT_PERCENT5_APPLY: 'discount.percent5:apply',
  DINING_OPEN: 'dining:open',
  TAKEAWAY_OPEN: 'takeaway:open',
  DELIVERY_OPEN: 'delivery:open',
  WORK_SHIFT_CLOSE: 'workShift:close',
  WORKDAY_CLOSE: 'workday:close',
  TABLES_EDIT: 'tables:edit',
  CHECK_WAITER_TRANSFER: 'check.waiter:transfer',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const permissionsList = [
  { name: PERMISSIONS.USERS_CREATE, description: 'Create new users' },
  { name: PERMISSIONS.USERS_READ, description: 'Read user list and details' },
  { name: PERMISSIONS.USERS_UPDATE, description: 'Update existing users' },
  { name: PERMISSIONS.USERS_DELETE, description: 'Delete users' },
  { name: PERMISSIONS.REPORTS_TODAY_VIEW, description: "View today's reports" },
  { name: PERMISSIONS.REPORTS_PERIOD_VIEW, description: 'View periodic reports' },
  { name: PERMISSIONS.CHECK_CREATE, description: 'Create checks' },
  { name: PERMISSIONS.CHECK_VOID, description: 'Void checks' },
  { name: PERMISSIONS.CHECK_CLOSED_VOID, description: 'Void closed checks' },
  { name: PERMISSIONS.CHECK_ITEM_VOID, description: 'Void items in checks' },
  { name: PERMISSIONS.CHECK_ITEM_PRINTED_VOID, description: 'Void printed items in checks' },
  { name: PERMISSIONS.CHECK_PRINT, description: 'Print checks' },
  { name: PERMISSIONS.CHECK_REPRINT, description: 'Reprint checks' },
  { name: PERMISSIONS.CHECK_CLOSE, description: 'Close checks' },
  { name: PERMISSIONS.CHECK_OFFICER_CLOSE, description: 'Close officer checks' },
  { name: PERMISSIONS.CHECK_SEPERATE, description: 'Separate checks' },
  { name: PERMISSIONS.CHECK_PRINTED_SEPERATE, description: 'Separate printed checks' },
  { name: PERMISSIONS.CHECK_ITEM_TRANSFER, description: 'Transfer check items' },
  { name: PERMISSIONS.CHECK_PRINTED_ITEM_TRANSFER, description: 'Transfer printed check items' },
  { name: PERMISSIONS.CHECK_TABLE_TRANSFER, description: 'Transfer check tables' },
  { name: PERMISSIONS.CHECK_MERGE, description: 'Merge checks' },
  { name: PERMISSIONS.CHECK_PRINTED_MERGE, description: 'Merge printed checks' },
  { name: PERMISSIONS.CHECK_COMP, description: 'Comp checks' },
  { name: PERMISSIONS.CHECK_PRINTED_COMP, description: 'Comp printed checks' },
  { name: PERMISSIONS.CHECK_ITEM_COMP, description: 'Comp check items' },
  { name: PERMISSIONS.CHECK_PRINTED_ITEM_COMP, description: 'Comp printed check items' },
  { name: PERMISSIONS.MINIMUM_CHARGE_APPLY, description: 'Apply minimum charge' },
  { name: PERMISSIONS.DISCOUNT_APPLY, description: 'Apply discount' },
  { name: PERMISSIONS.DISCOUNT_PRINTED_APPLY, description: 'Apply discount on printed checks' },
  { name: PERMISSIONS.DISCOUNT_VALUE_APPLY, description: 'Apply value discount' },
  { name: PERMISSIONS.DISCOUNT_PERCENT1_APPLY, description: 'Apply discount percent 1' },
  { name: PERMISSIONS.DISCOUNT_PERCENT2_APPLY, description: 'Apply discount percent 2' },
  { name: PERMISSIONS.DISCOUNT_PERCENT3_APPLY, description: 'Apply discount percent 3' },
  { name: PERMISSIONS.DISCOUNT_PERCENT4_APPLY, description: 'Apply discount percent 4' },
  { name: PERMISSIONS.DISCOUNT_PERCENT5_APPLY, description: 'Apply discount percent 5' },
  { name: PERMISSIONS.DINING_OPEN, description: 'Open dining checks' },
  { name: PERMISSIONS.TAKEAWAY_OPEN, description: 'Open takeaway checks' },
  { name: PERMISSIONS.DELIVERY_OPEN, description: 'Open delivery checks' },
  { name: PERMISSIONS.WORK_SHIFT_CLOSE, description: 'Close work shifts' },
  { name: PERMISSIONS.WORKDAY_CLOSE, description: 'Close workdays' },
  { name: PERMISSIONS.TABLES_EDIT, description: 'Manage sections and table layouts' },
  { name: PERMISSIONS.CHECK_WAITER_TRANSFER, description: 'Transfer checks to other waiters' }
];
